In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],
                [4,5,6],
                [7,8,9]])

df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [3]:
print(df.shape)
print(df.index)

(3, 3)
RangeIndex(start=0, stop=3, step=1)

In [4]:
df2 = pd.DataFrame([[1,32,34], [1,32,34], [1,32,34], [1,32,34]], index=[1,2,4,5], columns=["a","w",'e'])

df2

   a   w   e
1  1  32  34
2  1  32  34
4  1  32  34
5  1  32  34

In [5]:
wdf = pd.read_csv("weather_2012.csv")
wdf.head(5)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [6]:
print(wdf.shape)
print(wdf.index)

(8784, 8)
RangeIndex(start=0, stop=8784, step=1)

In [7]:
print(wdf.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
Date/Time             8784 non-null object
Temp (C)              8784 non-null float64
Dew Point Temp (C)    8784 non-null float64
Rel Hum (%)           8784 non-null int64
Wind Spd (km/h)       8784 non-null int64
Visibility (km)       8784 non-null float64
Stn Press (kPa)       8784 non-null float64
Weather               8784 non-null object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB
None

In [8]:
wdf['Temp (C)'].unique()

array([ -1.8,  -1.5,  -1.4,  -1.3,  -1. ,  -0.5,  -0.2,   0.2,   0.8,
         1.8,   2.6,   3. ,   3.8,   3.1,   3.2,   4. ,   4.4,   5.3,
         5.2,   4.6,   3.9,   3.7,   2.9,   2.3,   2. ,   1.9,   1.5,
         2.2,   1.7,   1.1,   0. ,  -0.7,  -2.1,  -4.1,  -4.8,  -5.6,
        -5.8,  -7. ,  -7.4,  -9. ,  -9.7, -10.5, -11.3, -12.6, -12.9,
       -13.3, -14. , -14.8, -15. , -15.3, -14.9, -15.1, -15.8, -16.3,
       -16.9, -17.3, -17. , -17.1, -17.5, -17.9, -18.1, -18.5, -18.6,
       -18.2, -17.8, -16.8, -15.2, -14.2, -13.7, -12.4, -10.2,  -9.4,
        -8.9,  -8.4,  -7.8,  -7.6,  -9.5,  -9.6,  -8.8,  -7.5,  -5.4,
        -5. ,  -8.2,  -7.1,  -6.1,  -6.6,  -6. ,  -4.7,  -4.4,  -5.1,
        -4.3,  -6.7,  -9.2,  -9.8,  -9.9, -10. , -10.6, -11.8, -12. ,
       -14.4, -12.3, -12.5, -11.7, -11.9, -11.2, -11.5, -11.6,  -9.3,
        -8.7,  -8.5,  -8.1,  -6.9,  -6.4,  -5.7,  -5.5,  -3.7,  -3.6,
        -3.1,  -3.2,  -3. ,   0.4,   0.6,  -0.6,  -1.7,  -3.5,  -5.9,
        -6.5,  -7.2,  -8. ,  -8.3,  -7.7,  -6.8,  -2.5,  -1.1,  -0.3,
         2.5,   1.4,   1.6,   1.2,   0.7,  -4. ,  -4.9,  -7.3,  -8.6,
       -10.7, -12.7, -13.4, -13.9, -14.7, -14.3, -12.2, -11.4, -10.8,
        -6.2,  -5.2,  -4.6,  -4.5,  -2.9, -18. , -16.7, -17.4, -17.7,
       -18.3, -19.6, -20. , -19.9, -20.3, -21.2, -21.1, -21.4, -20.7,
       -21. , -21.3, -23.2, -22.8, -23.3, -22.2, -20.6, -19.3, -16. ,
       -15.4, -16.2, -19.2, -18.7, -19.1, -13.6, -10.1, -10.4,  -5.3,
        -3.3,  -1.6,   2.1,   0.5, -10.9, -11.1, -11. , -10.3, -16.6,
       -14.6,  -4.2,  -3.9,  -6.3, -15.5, -15.9, -16.4, -16.1, -12.1,
       -13. , -17.6, -18.4, -17.2, -19.5, -19. , -14.5, -13.2,   2.7,
         3.3,   3.6,   3.5,   5. ,   4.2,   3.4,   2.8,   2.4,   1.3,
         1. ,  -0.1,  -0.4,  -2.8,  -7.9,  -3.4,  -3.8,  -0.8,   0.3,
         0.1,  -1.2,   0.9,  -0.9,  -2. ,  -1.9,  -2.2,  -2.3, -15.7,
       -13.5, -13.8,  -2.4, -13.1, -12.8,  -2.7,   5.8,   6.1,   5.4,
         6.5,   4.3,   6.4,   8.9,   9.3,   9.7,  11.4,   9.9,   5.5,
         6. ,   7.6,   6.8,   4.8,   6.2,   7.9,  10.1,  10. ,   5.7,
        10.3,   6.7,  10.2,  12.1,  12.7,  11.7,  11.5,  11.6,  11.3,
        10.5,  -2.6,   5.9,   9. ,   9.5,  10.9,  10.7,   9.1,   7.4,
         8.3,  10.6,  10.8,  12.3,  12.4,  11.8,   8.7,   9.2,   8.4,
         6.6,   7.5,   5.1,   4.9,   4.1,   8.1,   9.8,   8.8,   7.7,
        10.4,  11.9,  14.1,  17.3,  20. ,  21.7,  22.2,  22.7,  21.8,
        18.4,  17.1,  12.8,  13.4,  12.6,  11.2,  13.9,  15.6,  17.8,
        19.8,  18.5,  17. ,  16.3,  16.6,  15.9,  12.5,   7.2,   7.1,
         8. ,  14.9,  16.5,  21.5,  22.5,  23.3,  22. ,  19.7,  17.5,
        18.1,  16. ,  14.2,  14.3,  14. ,  13.8,  18.2,  20.2,  22.3,
        23.8,  24.7,  25.4,  25.5,  25.2,  20.7,  17.2,  16.4,  18. ,
        15.5,  15. ,  11. ,  13.2,  13.7,  15.4,  19.6,  20.4,  23. ,
        22.8,  21.4,  16.7,  15.1,  14.5,  16.2,  16.8,  14.7,   7.3,
         4.7,   6.3,   4.5,   8.2,   7. ,   6.9,   7.8,   5.6,   8.5,
         8.6,   9.4,  12.2,  13.5,  16.1,  13.6,  15.3,  14.8,  12. ,
        12.9,  13.1,  19.4,  14.6,  15.7,  14.4,  15.2,  19.3,  24.9,
        24.1,  24.8,  26.6,  27.4,  27.8,  27.3,  26.7,  26.4,  20.5,
        19.5,  19. ,  18.9,  17.4,  11.1,  15.8,  18.7,   9.6,  13. ,
        13.3,  16.9,  20.1,  20.6,  20.9,  21. ,  19.9,  19.2,  17.6,
        17.9,  18.6,  22.4,  23.9,  23.6,  18.8,  21.2,  21.9,  23.2,
        23.4,  23.5,  22.9,  18.3,  20.3,  20.8,  17.7,  19.1,  25.6,
        25.8,  26. ,  24.3,  21.6,  26.8,  28.6,  29.5,  30.9,  31.2,
        30.8,  29.2,  26.9,  25.9,  24. ,  28. ,  28.4,  28.8,  28.9,
        28.2,  27.7,  26.5,  21.1,  24.6,  26.1,  27.1,  27.6,  28.1,
        24.4,  23.1,  27.2,  26.2,  21.3,  22.1,  22.6,  24.2,  23.7,
        25.3,  28.7,  29.4,  30.1,  29.6,  29.1,  25. ,  24.5,  25.7,
        27. ,  27.9,  26.3,  28.5,  29.7,  31.7,  32.2,  32.3,  32.4,
        30.6,  25.1,  31.8,  31.6,  32.6,  33. ,  32.5,  32.1,  31.1,
        30.3,  27.5,  29. ,  29.8,  30.7,  30.2,  29.9,  28.3,  30.5,
        30.4,  31.9,  31.4,  32.7,  32.9,  31.5,  29.3,  30. ,  32. ,
        32.8,  -9.1])

In [9]:
wdf['Temp (C)'].nunique() #number of unique values in a column

533

In [10]:
wdf['Temp (C)'].value_counts()

 16.6    65
 1.1     58
 0.8     47
 1.5     45
 19.3    44
 21.1    43
 2.6     43
 0.4     41
 1.3     40
 14.6    39
 1.8     38
 8.4     38
 1.0     38
 20.4    37
 13.1    37
-4.3     37
 14.2    36
 0.6     36
 21.8    36
 0.7     36
 23.2    36
 3.0     36
 3.7     35
 12.8    35
 19.6    35
 22.2    35
 1.2     35
 18.2    35
 1.9     35
 15.4    34
         ..
-20.6     1
 30.0     1
-20.3     1
-17.6     1
-23.3     1
-19.6     1
-18.2     1
-21.0     1
-19.5     1
 31.8     1
-19.3     1
 32.9     1
-21.4     1
 32.8     1
-21.2     1
 32.4     1
-17.0     1
-23.2     1
 30.3     1
 32.3     1
-19.0     1
-20.0     1
-19.9     1
-22.8     1
 31.4     1
-19.1     1
-21.3     1
 32.7     1
 32.6     1
-17.7     1
Name: Temp (C), Length: 533, dtype: int64

In [11]:
wdf['Temp (C)'].value_counts()[16.6]

65

In [12]:
wdf.head(25)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [13]:
wdf[:25]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [14]:
wdf[:6:2][['Rel Hum (%)', 'Visibility (km)']]

   Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8

In [15]:
# Using loc
# NOTE: slice is `:5:2`, not 6 !
wdf.loc[:5:2, ['Rel Hum (%)', 'Visibility (km)']]

   Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8

In [16]:
# Using iloc
wdf.iloc[:6:2, [3,5]]

   Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8

In [17]:
# Basically, we want a way to "filter out" records that don't have the word "snow" (case insensitive) in the last column

snowed_filter = wdf['Weather'].str.lower().str.contains('snow')
wdf[snowed_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
50,2012-01-03 02:00:00,-10.5,-15.8,65,22,12.9,100.53,Snow Showers
51,2012-01-03 03:00:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
53,2012-01-03 05:00:00,-12.9,-19.1,60,22,25.0,100.76,Snow Showers
54,2012-01-03 06:00:00,-13.3,-19.3,61,19,25.0,100.85,Snow Showers
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
89,2012-01-04 17:00:00,-8.9,-13.2,71,9,4.8,100.76,Snow
90,2012-01-04 18:00:00,-8.9,-12.6,75,11,9.7,100.69,Snow
91,2012-01-04 19:00:00,-8.4,-12.7,71,9,16.1,100.65,Snow
92,2012-01-04 20:00:00,-7.8,-12.1,71,9,16.1,100.61,Snow
93,2012-01-04 21:00:00,-7.6,-11.6,73,7,11.3,100.54,Snow
94,2012-01-04 22:00:00,-9.5,-12.7,77,6,9.7,100.50,Snow
95,2012-01-04 23:00:00,-9.6,-12.6,79,6,9.7,100.42,Snow
96,2012-01-05 00:00:00,-8.8,-11.7,79,4,9.7,100.32,Snow
97,2012-01-05 01:00:00,-7.5,-10.2,81,0,9.7,100.29,Snow
98,2012-01-05 02:00:00,-5.4,-8.3,80,9,8.0,100.28,Snow
99,2012-01-05 03:00:00,-5.0,-7.7,81,11,9.7,100.24,Snow
100,2012-01-05 04:00:00,-4.1,-6.5,83,9,4.8,100.21,Snow
101,2012-01-05 05:00:00,-7.0,-9.5,82,4,4.0,100.19,Snow
102,2012-01-05 06:00:00,-8.2,-10.7,82,6,6.4,100.26,Snow
103,2012-01-05 07:00:00,-7.1,-9.7,82,9,9.7,100.31,Snow
104,2012-01-05 08:00:00,-6.1,-9.1,79,11,9.7,100.39,Snow
...,...,...,...,...,...,...,...,...
8730,2012-12-29 18:00:00,-9.3,-10.9,88,26,6.4,100.38,"Snow,Fog"
8731,2012-12-29 19:00:00,-9.5,-11.2,87,26,3.2,100.33,"Snow,Fog"
8732,2012-12-29 20:00:00,-9.7,-11.6,86,24,9.7,100.25,"Snow,Fog"
8733,2012-12-29 21:00:00,-9.8,-11.8,85,24,8.0,100.24,"Snow,Fog"
8734,2012-12-29 22:00:00,-10.1,-11.6,89,15,2.4,100.20,"Snow,Fog"
8735,2012-12-29 23:00:00,-10.0,-12.0,85,20,6.4,100.19,"Snow,Fog"
8736,2012-12-30 00:00:00,-9.6,-11.3,87,13,3.2,100.23,"Snow,Fog"
8737,2012-12-30 01:00:00,-9.4,-10.5,92,9,2.4,100.22,"Snow,Fog"
8738,2012-12-30 02:00:00,-9.3,-10.4,92,9,4.0,100.28,"Snow,Fog"
8739,2012-12-30 03:00:00,-9.1,-10.4,90,11,3.6,100.30,"Snow,Fog"
8740,2012-12-30 04:00:00,-9.3,-10.6,90,13,9.7,100.28,"Snow,Fog"
8741,2012-12-30 05:00:00,-9.1,-10.4,90,11,4.0,100.32,"Snow,Fog"
8742,2012-12-30 06:00:00,-9.3,-10.8,89,17,8.0,100.39,"Snow,Fog"
8767,2012-12-31 07:00:00,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8768,2012-12-31 08:00:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,2012-12-31 09:00:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,2012-12-31 10:00:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8771,2012-12-31 11:00:00,-6.7,-7.9,91,9,9.7,100.93,Snow
8772,2012-12-31 12:00:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,2012-12-31 13:00:00,-4.6,-6.6,86,4,12.9,100.63,Snow
8774,2012-12-31 14:00:00,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,2012-12-31 15:00:00,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,2012-12-31 16:00:00,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,2012-12-31 17:00:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,2012-12-31 18:00:00,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [18]:
df = wdf[(wdf['Wind Spd (km/h)'] > 24) & (wdf['Visibility (km)']> 25)]
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
109,2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
111,2012-01-05 15:00:00,-4.3,-12.0,55,26,48.3,100.52,Mainly Clear
350,2012-01-15 14:00:00,-16.0,-23.4,53,26,48.3,102.66,Mainly Clear
422,2012-01-18 14:00:00,-10.3,-17.6,55,28,48.3,101.19,Mainly Clear
423,2012-01-18 15:00:00,-10.4,-18.0,54,30,48.3,101.32,Mainly Clear

In [23]:
wdf2 = pd.read_csv('weather_2012.csv', parse_dates=True, index_col='Date/Time')
wdf2.head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
Date/Time,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [24]:
wdf2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8784 entries, 2012-01-01 00:00:00 to 2012-12-31 23:00:00
Data columns (total 7 columns):
Temp (C)              8784 non-null float64
Dew Point Temp (C)    8784 non-null float64
Rel Hum (%)           8784 non-null int64
Wind Spd (km/h)       8784 non-null int64
Visibility (km)       8784 non-null float64
Stn Press (kPa)       8784 non-null float64
Weather               8784 non-null object
dtypes: float64(4), int64(2), object(1)
memory usage: 549.0+ KB

In [30]:
 wdf2.loc['2012-01-06', 'Stn Press (kPa)'].head(5)

Date/Time
2012-01-06 00:00:00    100.81
2012-01-06 01:00:00    100.81
2012-01-06 02:00:00    100.84
2012-01-06 03:00:00    100.76
2012-01-06 04:00:00    100.70
Name: Stn Press (kPa), dtype: float64

In [42]:
#when snow was recorded
snow_filter = wdf2['Weather'].str.lower().str.contains('snow')
wdf2[snow_filter].head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
Date/Time,,,,,,,
2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers

In [45]:
#wind speed was above 24 and visibility was 25
wind_visibility_filter = (wdf2['Wind Spd (km/h)'] > 24) & (wdf2['Visibility (km)'] == 25)
wdf2[wind_visibility_filter]

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
Date/Time,,,,,,,
2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
2012-01-02 04:00:00,2.9,-2.3,69,32,25.0,99.26,Mostly Cloudy
2012-01-02 05:00:00,2.6,-2.3,70,32,25.0,99.21,Mostly Cloudy
2012-01-02 06:00:00,2.3,-2.6,70,26,25.0,99.18,Mostly Cloudy
2012-01-02 07:00:00,2.0,-2.9,70,33,25.0,99.14,Mostly Cloudy
2012-01-02 18:00:00,-4.1,-11.4,57,28,25.0,99.86,Mostly Cloudy
2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
2012-01-03 03:00:00,-11.3,-18.7,54,33,25.0,100.61,Snow Showers
2012-01-08 00:00:00,0.6,-3.2,76,32,25.0,100.72,Cloudy
2012-01-08 01:00:00,-0.6,-4.6,74,32,25.0,100.80,Mostly Cloudy
2012-01-08 02:00:00,-1.7,-6.2,71,30,25.0,100.98,Mostly Cloudy
2012-01-08 03:00:00,-3.5,-8.3,69,32,25.0,101.13,Mainly Clear
2012-01-10 00:00:00,2.5,-5.2,57,30,25.0,100.38,Cloudy
2012-01-10 01:00:00,2.3,-3.4,66,35,25.0,100.28,Snow
2012-01-10 03:00:00,1.6,-2.0,77,28,25.0,100.16,Snow
2012-01-10 04:00:00,1.2,-1.7,81,26,25.0,100.07,Cloudy
2012-01-11 19:00:00,-11.8,-19.2,54,30,25.0,101.43,Mostly Cloudy
2012-01-12 02:00:00,-9.4,-15.0,64,26,25.0,101.08,Cloudy
2012-01-12 03:00:00,-9.0,-14.7,63,33,25.0,101.02,Cloudy
2012-01-12 05:00:00,-8.0,-13.7,64,30,25.0,100.81,Cloudy
2012-01-12 06:00:00,-7.6,-13.1,65,28,25.0,100.76,Cloudy
2012-01-12 22:00:00,-4.1,-6.8,81,26,25.0,99.47,Snow
2012-01-14 07:00:00,-16.8,-22.2,63,26,25.0,100.73,Mostly Cloudy
2012-01-18 01:00:00,3.7,-2.1,66,83,25.0,98.36,Mostly Cloudy
2012-01-18 02:00:00,0.5,-4.0,72,70,25.0,98.62,Mostly Cloudy
...,...,...,...,...,...,...,...
2012-12-05 22:00:00,-1.6,-9.5,55,26,25.0,102.01,Mostly Cloudy
2012-12-09 20:00:00,-2.2,-7.2,69,28,25.0,102.11,Cloudy
2012-12-09 22:00:00,-3.0,-8.2,67,28,25.0,101.78,Cloudy
2012-12-09 23:00:00,-3.6,-8.6,68,32,25.0,101.64,Cloudy
2012-12-11 01:00:00,0.0,-3.6,77,28,25.0,99.99,Cloudy
2012-12-15 23:00:00,-9.9,-15.0,66,26,25.0,102.38,Cloudy
2012-12-16 02:00:00,-10.1,-14.6,70,28,25.0,102.17,Cloudy
2012-12-16 03:00:00,-10.1,-14.5,70,28,25.0,102.15,Cloudy
2012-12-16 06:00:00,-9.9,-14.6,68,35,25.0,101.93,Cloudy
2012-12-16 07:00:00,-9.8,-14.9,66,32,25.0,101.89,Cloudy
2012-12-20 23:00:00,1.2,-2.1,79,28,25.0,100.69,Cloudy
2012-12-21 00:00:00,1.9,-2.1,75,26,25.0,100.60,"Rain,Snow Grains"
2012-12-21 18:00:00,1.4,0.3,92,46,25.0,97.56,Rain
2012-12-23 01:00:00,-7.9,-11.8,74,32,25.0,100.27,Snow Showers
2012-12-23 02:00:00,-8.2,-12.5,71,30,25.0,100.36,Mostly Cloudy
2012-12-23 03:00:00,-8.2,-12.4,72,30,25.0,100.40,Cloudy
2012-12-23 04:00:00,-8.3,-12.7,71,28,25.0,100.43,Cloudy
2012-12-23 05:00:00,-8.5,-13.2,69,30,25.0,100.49,Cloudy
2012-12-23 06:00:00,-8.4,-12.3,73,26,25.0,100.51,Cloudy
2012-12-26 19:00:00,-9.6,-13.1,76,39,25.0,102.03,Cloudy
2012-12-26 20:00:00,-10.3,-12.9,81,28,25.0,101.88,Cloudy
2012-12-26 22:00:00,-9.7,-12.8,78,37,25.0,101.70,Cloudy
2012-12-27 00:00:00,-9.8,-12.5,81,30,25.0,101.46,Cloudy
2012-12-27 01:00:00,-9.4,-12.2,80,26,25.0,101.37,Cloudy
2012-12-27 02:00:00,-8.5,-11.3,80,30,25.0,101.31,Cloudy
2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [51]:
add_10 = wdf2["Wind Spd (km/h)"] + 100
print(add_10.head())
mult_2 = weather_df2['Visibility (km)'] * 2
print(mult_2.head())
temperature = weather_df2["Temp (C)"] + weather_df2["Dew Point Temp (C)"]
print(temperature.head())

Date/Time
2012-01-01 00:00:00    104
2012-01-01 01:00:00    104
2012-01-01 02:00:00    107
2012-01-01 03:00:00    106
2012-01-01 04:00:00    107
Name: Wind Spd (km/h), dtype: int64
Date/Time
2012-01-01 00:00:00    16.0
2012-01-01 01:00:00    16.0
2012-01-01 02:00:00     8.0
2012-01-01 03:00:00     8.0
2012-01-01 04:00:00     9.6
Name: Visibility (km), dtype: float64
Date/Time
2012-01-01 00:00:00   -5.7
2012-01-01 01:00:00   -5.5
2012-01-01 02:00:00   -5.2
2012-01-01 03:00:00   -4.7
2012-01-01 04:00:00   -4.8
dtype: float64

In [58]:
wdf2['Visibility (km)'].describe()

count    8784.000000
mean       27.664447
std        12.622688
min         0.200000
25%        24.100000
50%        25.000000
75%        25.000000
max        48.300000
Name: Visibility (km), dtype: float64

In [59]:
wdf2.describe(include='all')

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784
unique,NaN,NaN,NaN,NaN,NaN,NaN,50
top,NaN,NaN,NaN,NaN,NaN,NaN,Mainly Clear
freq,NaN,NaN,NaN,NaN,NaN,NaN,2106
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623,NaN
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005,NaN
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000,NaN
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000,NaN
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000,NaN
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000,NaN
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000,NaN

In [61]:
wdf2['Weather'].describe()

count             8784
unique              50
top       Mainly Clear
freq              2106
Name: Weather, dtype: object

In [63]:
wdf2['Visibility (km)'].min()

0.2

In [68]:
def minus2(x):
    return x-200

wdf2['Visibility (km)'].apply(minus2).head()

Date/Time
2012-01-01 00:00:00   -192.0
2012-01-01 01:00:00   -192.0
2012-01-01 02:00:00   -196.0
2012-01-01 03:00:00   -196.0
2012-01-01 04:00:00   -195.2
Name: Visibility (km), dtype: float64

In [71]:
# Adding Columns
visibility_in_meter = wdf2["Visibility (km)"] * 1000  
wdf2["Visibility (m)"] = visibility_in_meter

wdf2.head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,Visibility (m)
Date/Time,,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,8000.0
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,8000.0
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",4000.0
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",4000.0
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,4800.0

In [78]:
# Renaming Columns
wdf2.rename(columns={'Visibility (m)': 'Visibility (meters)'}, inplace=True)
wdf2.head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,Visibility (meters)
Date/Time,,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,8000.0
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,8000.0
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",4000.0
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",4000.0
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,4800.0

In [80]:
wdf2.drop(columns=['Visibility (meters)'], inplace=True)
wdf2.head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
Date/Time,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [82]:
#SORTING

sorted_by_temp = wdf2.sort_values('Temp (C)', ascending=True)  # can be inplace as well
sorted_by_temp.head()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
Date/Time,,,,,,,
2012-01-15 08:00:00,-23.3,-28.5,62,7,24.1,102.45,Clear
2012-01-15 06:00:00,-23.2,-28.5,62,7,25.0,102.28,Mostly Cloudy
2012-01-15 07:00:00,-22.8,-28.0,62,9,25.0,102.37,Mainly Clear
2012-01-15 09:00:00,-22.2,-27.8,60,9,48.3,102.57,Mainly Clear
2012-01-15 02:00:00,-21.4,-26.6,63,9,25.0,101.99,Cloudy

In [113]:
#top 10 hottest values and their counts

hottest = wdf['Temp (C)'].sort_values(ascending=False).value_counts(sort=False)
hottest.iloc[:10]

33.0     2
32.0     1
28.0    11
24.0    17
22.0    24
20.0    34
16.0    29
14.0    25
13.0    25
12.0    26
Name: Temp (C), dtype: int64

In [115]:
#mean temperature recorded by month
#Solution 1
mean_temperatures = {}

for month in range(1, 13):
    mean_temperatures[month] = weather_df2.loc[weather_df2.index.month == month, 'Temp (C)'].mean()

pd.Series(mean_temperatures)

{1: -7.371505376344083,
 2: -4.2250000000000005,
 3: 3.1212365591397853,
 4: 7.0093055555555575,
 5: 16.2377688172043,
 6: 20.134027777777785,
 7: 22.790053763440845,
 8: 22.279301075268787,
 9: 16.484444444444463,
 10: 10.954973118279568,
 11: 0.9313888888888887,
 12: -3.3063172043010765}

In [123]:
#PIVOT TABLES
#Solution2

mean_temp = wdf2.pivot_table(values=['Temp (C)'],
                             index=wdf2.index.month,
                             aggfunc='mean') #np.mean
mean_temp``

            Temp (C)
Date/Time
1          -7.371505
2          -4.225000
3           3.121237
4           7.009306
5          16.237769
6          20.134028
7          22.790054
8          22.279301
9          16.484444
10         10.954973
11          0.931389
12         -3.306317

In [129]:
#GroupBy
wdf2.groupby(wdf2.index.month).agg(np.mean).reset_index()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
0,1,-7.371505,-12.294758,68.383065,18.108871,22.100269,101.005349
1,2,-4.225000,-9.221695,68.956897,14.837644,25.182184,101.142414
2,3,3.121237,-3.488575,64.862903,14.514785,26.177957,101.335255
3,4,7.009306,-1.934583,56.150000,17.369444,31.777083,100.716833
4,5,16.237769,8.080780,61.760753,12.846774,29.418548,101.057164
5,6,20.134028,11.738056,60.643056,14.681944,32.104167,100.784222
6,7,22.790054,14.595430,62.017473,11.887097,33.655108,100.828333
7,8,22.279301,15.644758,67.943548,13.931452,30.192608,100.927097
8,9,16.484444,10.757917,71.165278,14.108333,30.603472,101.087903
9,10,10.954973,6.533468,75.731183,15.475806,25.111022,100.909368
10,11,0.931389,-4.179306,69.984722,13.973611,26.077083,101.658306
11,12,-3.306317,-6.129032,81.299731,17.614247,19.733199,101.174409